import scrapy
import csv
class BenhnguoilonPySpider(scrapy.Spider):
    name = "BenhNguoiLon.py"
    allowed_domains = ["vnexpress.net"]
    start_urls = [
        'https://vnexpress.net/thay-van-hai-la-cho-benh-nhan-thap-tim-lau-nam-4786873.html',
        'https://vnexpress.net/nhan-giap-tien-trien-ung-thu-4785610.html',
        'https://vnexpress.net/huyet-khoi-tinh-mach-dui-do-hoi-chung-may-thurner-4785159.html',
        'https://vnexpress.net/cuong-giap-loi-mat-do-benh-basedow-4784710.html',
        'https://vnexpress.net/phu-bach-huyet-khien-chan-trai-to-gap-doi-chan-phai-4782505.html',
        'https://vnexpress.net/mo-bac-cau-mach-vanh-khi-trai-tim-van-dap-4781937.html',
        'https://vnexpress.net/nguoi-dan-ong-nang-110-kg-bien-chung-nhoi-mau-co-tim-4781306.html',
        'https://vnexpress.net/nong-mach-cuu-cu-ba-97-tuoi-nhoi-mau-co-tim-4781084.html',
        'https://vnexpress.net/mang-nhen-tinh-mach-bao-vay-u-long-nguc-4780961.html',
        'https://vnexpress.net/kham-viem-xoang-phat-hien-u-long-nguc-to-bang-qua-le-4779743.html',
        'https://vnexpress.net/bit-lo-thong-tim-cho-nguoi-mac-nhieu-benh-nen-4779161.html',
        'https://vnexpress.net/so-cuu-dung-cach-nguoi-dot-quy-nhoi-mau-co-tim-4779280.html'
        'https://vnexpress.net/mo-tham-my-nhan-tuyen-giap-4776624.html',
        'https://vnexpress.net/chan-sung-to-boi-huyet-khoi-tinh-mach-dui-4776390.html',
        'https://vnexpress.net/chua-ung-thu-phoi-phat-hien-them-benh-mach-vanh-4775908.html',
        'https://vnexpress.net/ba-nhanh-mach-vanh-tac-nghen-do-tang-cholesterol-mau-di-truyen-4774917.html',
        'https://vnexpress.net/6-cach-giam-cholesterol-4774356.html',
        'https://vnexpress.net/u-tim-4773956.html',
        'https://vnexpress.net/u-o-dinh-phoi-to-gap-doi-sau-16-nam-4773348.html',
        'https://vnexpress.net/suy-tim-sau-nhieu-nam-suy-than-man-4773335.html',
        'https://vnexpress.net/huyet-ap-tay-trai-thap-hon-tay-phai-do-hep-mach-mau-nao-4770925.html',
        'https://vnexpress.net/huyet-ap-cao-khong-ha-do-boc-tach-dong-mach-chu-4771203.html',
        'https://vnexpress.net/song-khoe-sau-13-nam-suy-tim-4771677.html',
        'https://vnexpress.net/cu-ong-ngung-tim-do-bien-chung-viem-co-tim-4772887.html',
        'https://vnexpress.net/khi-nao-can-phau-thuat-ho-van-tim-4767272.html',
        'https://vnexpress.net/phau-thuat-boc-xo-vua-dong-mach-ngan-dot-quy-4767563.html',
        'https://vnexpress.net/tuong-ung-thu-hoa-nhan-giap-lanh-tinh-4767968.html',
        'https://vnexpress.net/kho-tho-do-vo-ken-khi-phoi-4769681.html',
        'https://vnexpress.net/dau-nguc-canh-bao-cac-benh-gi-4764693.html',
        'https://vnexpress.net/45-phut-cuu-nguoi-dan-ong-nhoi-mau-co-tim-4764968.html',
        'https://vnexpress.net/te-tay-boi-hoi-chung-loi-thoat-long-nguc-4766033.html',
        'https://vnexpress.net/tac-nghen-dong-mach-khien-nguoi-dan-ong-suyt-nhoi-mau-co-tim-4766297.html',
        'https://vnexpress.net/nhan-giap-bien-thanh-buou-to-sau-30-nam-4762262.html',
        'https://vnexpress.net/nguc-lom-thanh-ho-2-cm-4762320.html',
        'https://vnexpress.net/dau-nguc-trai-bao-hieu-nhoi-mau-co-tim-ma-khong-biet-4763777.html',
        'https://vnexpress.net/ba-yeu-to-lam-tang-nguy-co-mac-benh-tim-o-nguoi-tre-4763953.html',
        'https://vnexpress.net/thuoc-la-hai-tim-the-nao-4760035.html',
        'https://vnexpress.net/bat-ngo-phat-hien-nhoi-mau-co-tim-tham-lang-4760662.html',
        'https://vnexpress.net/quy-tac-5-an-5-tranh-giup-dieu-hoa-mo-mau-4761003.html',
        'https://vnexpress.net/tai-sao-suy-tinh-mach-chi-duoi-gay-te-chan-4761789.html',
        'https://vnexpress.net/bom-keo-chua-suy-tinh-mach-cho-nguoi-phu-nu-4757624.html',
        'https://vnexpress.net/viem-co-tim-cap-4752427.html',
        'https://vnexpress.net/huyet-khoi-lap-day-mach-vanh-sau-20-nam-hut-thuoc-la-4758708.html',
        'https://vnexpress.net/tai-hep-mach-vanh-sau-dat-stent-4759311.html',
        'https://vnexpress.net/cong-nghe-cao-phau-thuat-mach-mau-cuu-mang-nhieu-ca-benh-nang-4756026.html',
        'https://vnexpress.net/benh-mach-vanh-thu-pham-gay-nhoi-mau-co-tim-4756327.html',
        'https://vnexpress.net/phu-chan-voi-sau-nhieu-nam-dieu-tri-ung-thu-4756741.html',
        'https://vnexpress.net/thieu-nu-lom-nguc-nguy-co-suy-tim-4757083.html',
        'https://vnexpress.net/co-phinh-to-boi-nang-giap-4741323.html',
        'https://vnexpress.net/xep-phoi-gay-7-xuong-suon-sau-cu-nga-cau-thang-4740863.html',
        'https://vnexpress.net/an-uong-gi-de-tang-huyet-ap-4739520.html',
        'https://vnexpress.net/dau-nguc-tuong-benh-tim-hoa-ung-thu-4739164.html',
        'https://vnexpress.net/dau-hieu-nao-canh-bao-benh-tim-khong-nen-lo-la-4734788.html',
        'https://vnexpress.net/bieu-hien-nao-o-da-mong-canh-bao-tim-khong-khoe-4735390.html',
        'https://vnexpress.net/mach-mau-chan-tac-nghen-khien-cu-ong-khong-the-di-lai-4735573.html',
        'https://vnexpress.net/hut-thuoc-la-co-lam-tang-nguy-co-dot-quy-4733800.html',
        'https://vnexpress.net/u-giap-to-nhu-qua-trung-ga-gay-kho-nuot-4733274.html',
        'https://vnexpress.net/dau-hieu-dien-hinh-cua-con-nhoi-mau-co-tim-4733879.html',
        'https://vnexpress.net/tang-huyet-ap-co-dan-toi-dot-quy-4734412.html',
        'https://vnexpress.net/mach-vanh-tac-nghen-nang-khien-cu-ong-suy-tim-4743670.html',
        'https://vnexpress.net/mang-xo-vua-bit-kin-mach-vanh-nguoi-dan-ong-4744257.html',
        'https://vnexpress.net/ai-nen-lam-xet-nghiem-dong-mau-4744603.html',
        'https://vnexpress.net/thieu-mau-co-tim-nhieu-ngay-ma-khong-biet-4746074.html',
        'https://vnexpress.net/co-phinh-to-boi-nang-giap-4741323.html',
        'https://vnexpress.net/kha-nang-song-sot-cua-nguoi-bi-nhoi-mau-co-tim-4741899.html',
        'https://vnexpress.net/nhip-tim-that-thuong-boi-mach-vanh-voi-hoa-nang-4742856.html',
        'https://vnexpress.net/dat-stent-chu-y-khoi-thong-mach-mau-xoan-van-4743275.html',
        'https://vnexpress.net/thoi-quen-ngu-tot-cho-tim-4743592.html',
        'https://vnexpress.net/phat-hien-ung-thu-phoi-do-dot-bien-gene-4734643.html',
        'https://vnexpress.net/so-cuu-nhoi-mau-co-tim-dung-cach-tranh-dot-tu-4738165.html',
        'https://vnexpress.net/dong-mach-chu-nguc-phinh-to-doa-vo-4738101.html',
        'https://vnexpress.net/suyt-dot-tu-do-tac-hai-mach-mau-lon-nuoi-tim-4737410.html',
        'https://vnexpress.net/hai-lan-can-thiep-cho-nhac-cong-bi-nhoi-mau-co-tim-4737084.html',
        'https://vnexpress.net/benh-tim-co-anh-huong-den-sinh-ly-4731612.html',
        'https://vnexpress.net/nhieu-nguoi-bi-nhoi-mau-co-tim-ma-khong-biet-4732615.html',
        'https://vnexpress.net/co-phinh-to-boi-nang-giap-4741323.html',
        'https://vnexpress.net/mach-mau-chan-tac-nghen-khien-cu-ong-khong-the-di-lai-4735573.html',
        'https://vnexpress.net/nhan-giap-bien-thanh-buou-to-sau-30-nam-4762262.html',
        'https://vnexpress.net/nong-mach-cuu-cu-ba-97-tuoi-nhoi-mau-co-tim-4781084.html',
        'https://vnexpress.net/mang-nhen-tinh-mach-bao-vay-u-long-nguc-4780961.html',
        'https://vnexpress.net/quy-tac-5-an-5-tranh-giup-dieu-hoa-mo-mau-4761003.html',
        'https://vnexpress.net/so-cuu-dung-cach-nguoi-dot-quy-nhoi-mau-co-tim-4779280.html'
        'https://vnexpress.net/45-phut-cuu-nguoi-dan-ong-nhoi-mau-co-tim-4764968.html',
        'https://vnexpress.net/thoi-quen-ngu-tot-cho-tim-4743592.html',
        'https://vnexpress.net/huyet-ap-tay-trai-thap-hon-tay-phai-do-hep-mach-mau-nao-4770925.html',
        'https://vnexpress.net/so-cuu-nhoi-mau-co-tim-dung-cach-tranh-dot-tu-4738165.html',
        'https://vnexpress.net/ba-nhanh-mach-vanh-tac-nghen-do-tang-cholesterol-mau-di-truyen-4774917.html',
        'https://vnexpress.net/te-tay-boi-hoi-chung-loi-thoat-long-nguc-4766033.html',
        'https://vnexpress.net/thay-van-hai-la-cho-benh-nhan-thap-tim-lau-nam-4786873.html',
        'https://vnexpress.net/huyet-khoi-tinh-mach-dui-do-hoi-chung-may-thurner-4785159.html',
        'https://vnexpress.net/nhan-giap-tien-trien-ung-thu-4785610.html',
        'https://vnexpress.net/mang-xo-vua-bit-kin-mach-vanh-nguoi-dan-ong-4744257.html',
        'https://vnexpress.net/mo-bac-cau-mach-vanh-khi-trai-tim-van-dap-4781937.html',
        'https://vnexpress.net/tai-hep-mach-vanh-sau-dat-stent-4759311.html',
        'https://vnexpress.net/mo-tham-my-nhan-tuyen-giap-4776624.html',
        'https://vnexpress.net/an-uong-gi-de-tang-huyet-ap-4739520.html',
        'https://vnexpress.net/suyt-dot-tu-do-tac-hai-mach-mau-lon-nuoi-tim-4737410.html',
        'https://vnexpress.net/u-o-dinh-phoi-to-gap-doi-sau-16-nam-4773348.html',
        'https://vnexpress.net/cu-ong-ngung-tim-do-bien-chung-viem-co-tim-4772887.html',
        'https://vnexpress.net/khi-nao-can-phau-thuat-ho-van-tim-4767272.html',
        'https://vnexpress.net/phau-thuat-boc-xo-vua-dong-mach-ngan-dot-quy-4767563.html',
        'https://vnexpress.net/thieu-mau-co-tim-nhieu-ngay-ma-khong-biet-4746074.html',
        'https://vnexpress.net/chua-ung-thu-phoi-phat-hien-them-benh-mach-vanh-4775908.html',
        'https://vnexpress.net/dau-nguc-canh-bao-cac-benh-gi-4764693.html',
        'https://vnexpress.net/chan-sung-to-boi-huyet-khoi-tinh-mach-dui-4776390.html',
        'https://vnexpress.net/mach-vanh-tac-nghen-nang-khien-cu-ong-suy-tim-4743670.html',
        'https://vnexpress.net/tang-huyet-ap-co-dan-toi-dot-quy-4734412.html',
        'https://vnexpress.net/bat-ngo-phat-hien-nhoi-mau-co-tim-tham-lang-4760662.html',
        'https://vnexpress.net/phu-bach-huyet-khien-chan-trai-to-gap-doi-chan-phai-4782505.html',
        'https://vnexpress.net/ba-yeu-to-lam-tang-nguy-co-mac-benh-tim-o-nguoi-tre-4763953.html',
        'https://vnexpress.net/nhip-tim-that-thuong-boi-mach-vanh-voi-hoa-nang-4742856.html',
        'https://vnexpress.net/bit-lo-thong-tim-cho-nguoi-mac-nhieu-benh-nen-4779161.html',
        'https://vnexpress.net/cuong-giap-loi-mat-do-benh-basedow-4784710.html',
        'https://vnexpress.net/kho-tho-do-vo-ken-khi-phoi-4769681.html',
        'https://vnexpress.net/u-giap-to-nhu-qua-trung-ga-gay-kho-nuot-4733274.html',
        'https://vnexpress.net/phu-chan-voi-sau-nhieu-nam-dieu-tri-ung-thu-4756741.html',
        'https://vnexpress.net/dong-mach-chu-nguc-phinh-to-doa-vo-4738101.html',
        'https://vnexpress.net/co-phinh-to-boi-nang-giap-4741323.html',
        'https://vnexpress.net/thuoc-la-hai-tim-the-nao-4760035.html',
        'https://vnexpress.net/phat-hien-ung-thu-phoi-do-dot-bien-gene-4734643.html',
        'https://vnexpress.net/thieu-nu-lom-nguc-nguy-co-suy-tim-4757083.html',
        'https://vnexpress.net/dat-stent-chu-y-khoi-thong-mach-mau-xoan-van-4743275.html',
        'https://vnexpress.net/ai-nen-lam-xet-nghiem-dong-mau-4744603.html',
        'https://vnexpress.net/hai-lan-can-thiep-cho-nhac-cong-bi-nhoi-mau-co-tim-4737084.html',
        'https://vnexpress.net/benh-tim-co-anh-huong-den-sinh-ly-4731612.html',
        'https://vnexpress.net/tac-nghen-dong-mach-khien-nguoi-dan-ong-suyt-nhoi-mau-co-tim-4766297.html',
        'https://vnexpress.net/nhieu-nguoi-bi-nhoi-mau-co-tim-ma-khong-biet-4732615.html',
        'https://vnexpress.net/xep-phoi-gay-7-xuong-suon-sau-cu-nga-cau-thang-4740863.html',
        'https://vnexpress.net/6-cach-giam-cholesterol-4774356.html',
        'https://vnexpress.net/bieu-hien-nao-o-da-mong-canh-bao-tim-khong-khoe-4735390.html',
        'https://vnexpress.net/benh-mach-vanh-thu-pham-gay-nhoi-mau-co-tim-4756327.html',
        'https://vnexpress.net/nguoi-dan-ong-nang-110-kg-bien-chung-nhoi-mau-co-tim-4781306.html',
        'https://vnexpress.net/tai-sao-suy-tinh-mach-chi-duoi-gay-te-chan-4761789.html',
        'https://vnexpress.net/viem-co-tim-cap-4752427.html',
        'https://vnexpress.net/suy-tim-sau-nhieu-nam-suy-than-man-4773335.html',
        'https://vnexpress.net/nguc-lom-thanh-ho-2-cm-4762320.html',
        'https://vnexpress.net/dau-hieu-nao-canh-bao-benh-tim-khong-nen-lo-la-4734788.html',
        'https://vnexpress.net/hut-thuoc-la-co-lam-tang-nguy-co-dot-quy-4733800.html',
        'https://vnexpress.net/kham-viem-xoang-phat-hien-u-long-nguc-to-bang-qua-le-4779743.html',
        'https://vnexpress.net/u-tim-4773956.html',
        'https://vnexpress.net/huyet-khoi-lap-day-mach-vanh-sau-20-nam-hut-thuoc-la-4758708.html',
        'https://vnexpress.net/cong-nghe-cao-phau-thuat-mach-mau-cuu-mang-nhieu-ca-benh-nang-4756026.html',
        'https://vnexpress.net/huyet-ap-cao-khong-ha-do-boc-tach-dong-mach-chu-4771203.html',
        'https://vnexpress.net/dau-nguc-trai-bao-hieu-nhoi-mau-co-tim-ma-khong-biet-4763777.html',
        'https://vnexpress.net/dau-hieu-dien-hinh-cua-con-nhoi-mau-co-tim-4733879.html',
        'https://vnexpress.net/dau-nguc-tuong-benh-tim-hoa-ung-thu-4739164.html',
        'https://vnexpress.net/kha-nang-song-sot-cua-nguoi-bi-nhoi-mau-co-tim-4741899.html',
        'https://vnexpress.net/tuong-ung-thu-hoa-nhan-giap-lanh-tinh-4767968.html',
        'https://vnexpress.net/song-khoe-sau-13-nam-suy-tim-4771677.html',
        'https://vnexpress.net/bom-keo-chua-suy-tinh-mach-cho-nguoi-phu-nu-4757624.html',
    ]


    def parse(self, response):
        # Extract data from the webpage
        data = {
            'title': response.css('h1.title-detail::text').get(),
            'content': ''.join(response.css('article.fck_detail p::text').getall()), # ghép các đoạn văn lại
            'author': response.css('p strong::text').get(),
            'date': response.css('span.date::text').get(),
            'location': response.css('span.location-stamp::text').get(),
            'url': response.url,
        }

        # Save the extracted data to a CSV file
        with open('BenhNguoiLon.csv', 'a', newline='', encoding='utf-8') as csvfile:
            fieldnames = ['title', 'content', 'author', 'date', 'location', 'url']
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

            if csvfile.tell() == 0:
                writer.writeheader()

            writer.writerow(data)

        # Follow the next page link (if exists)
        next_page = response.css('.next a::attr(href)').get()
        if next_page:
            yield response.follow(next_page, self.parse)